// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itaaesuxxaoqovtvbtic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0YWFlc3V4eGFvcW92dHZidGljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTUwNTEsImV4cCI6MjA2OTg3MTA1MX0.QKD5ecTLjHcr5Ps_UCbDZmwl4QXoMYy6XT4I6rL7Ud8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});